# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
