# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_auto_20170724_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
    ]
